services:
  notes-backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notes_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=eswar2005
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=notes_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eswar2005
